"""Generate consolidated LaTeX tables for the compacted document.

Reads from outputs/*.csv (already generated by the pipeline)
and writes merged .tex files to docs/tables/.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = ROOT / "outputs"
TABLES = ROOT / "docs" / "tables"
sys.path.insert(0, str(ROOT))
from src.latex_export import fmt_num, fmt_pval, fmt_coef_se_pval, stars, wrap_table, wrap_minipage_table


# ── Helpers ──────────────────────────────────────────────
def read(name: str) -> pd.DataFrame:
    return pd.read_csv(OUTPUTS / name)


def fmt_coef_se(coef: float, se: float, pval: float) -> str:
    return f"{fmt_num(coef, 4)}{stars(pval)}\\\\({fmt_num(se, 4)})"


def write_tex(name: str, content: str) -> Path:
    path = TABLES / name
    path.write_text(content)
    print(f"  Wrote {path.name}")
    return path


# ════════════════════════════════════════════════════════════
# TABLE 1: Main Results (M1–M7b) + Diagnostics
# ════════════════════════════════════════════════════════════
def generate_main_table() -> str:
    coefs = read("model_coefficients.csv")
    fe = coefs[coefs["estimator"] == "fixed_effects_driscoll_kraay"]
    fs = read("model_fit_stats.csv")
    fe_fs = fs[fs["estimator"] == "fixed_effects_driscoll_kraay"]
    diag = read("model_diagnostics.csv")
    vif = read("model_vif.csv")
    pb = read("model_panel_balance_summary.csv")

    # Model ordering — M6a = M4+tourism, M6b = M2+tourism, M7a = M4+HC, M7b = M2+HC
    model_ids = [
        "M1_baseline_liquidity",
        "M2_main_monetary_policy",
        "M3_lagged_main_model",
        "M4_real_interest_robustness",
        "M5_lending_rate_robustness",
        # Panel B
        "M6_tourism_robustnessa_from_M4_real_interest_robustness",
        "M6_tourism_robustnessb_from_M2_main_monetary_policy",
        "M7_human_capital_robustnessa_from_M4_real_interest_robustness",
        "M7_human_capital_robustnessb_from_M2_main_monetary_policy",
    ]
    # Verify all exist
    model_ids = [m for m in model_ids if m in fe["model_id"].unique()]

    short_labels = {
        "M1_baseline_liquidity": "M1",
        "M2_main_monetary_policy": "M2",
        "M3_lagged_main_model": "M3",
        "M4_real_interest_robustness": "M4",
        "M5_lending_rate_robustness": "M5",
        "M6_tourism_robustnessa_from_M4_real_interest_robustness": "M6a",
        "M6_tourism_robustnessb_from_M2_main_monetary_policy": "M6b",
        "M7_human_capital_robustnessa_from_M4_real_interest_robustness": "M7a",
        "M7_human_capital_robustnessb_from_M2_main_monetary_policy": "M7b",
    }

    ncols_a = 6  # Label + M1-M5
    ncols_b = 5  # Label + M6a-M7b

    # ── Panel A: M1–M5 ──
    panel_a_ids = model_ids[:5]
    panel_b_ids = model_ids[5:]

    col_headers_a = " & ".join(short_labels[m] for m in panel_a_ids)
    col_headers_b = " & ".join(short_labels[m] for m in panel_b_ids)

    # Sub-header row
    sub_a = r" & \multicolumn{4}{c}{Headline Models} & \\"
    sub_b = r" & \multicolumn{4}{c}{Extended Models} & \\"

    def row_coef(term: str, label: str, models: list[str]) -> list[str] | None:
        """Return [label, coef1, se1, coef2, se2, ...] or None if absent in all."""
        parts = [label]
        has_any = False
        for mid in models:
            r = fe[(fe["model_id"] == mid) & (fe["term"] == term)]
            if r.empty:
                parts.extend(["", ""])
            else:
                has_any = True
                rr = r.iloc[0]
                parts.append(f"{fmt_num(rr['coef'], 4)}{stars(rr['p_value'])}")
                parts.append(f"({fmt_num(rr['std_error'], 4)})")
        return parts if has_any else None

    def row_single(metric_callable, label: str, models: list[str]) -> list[str]:
        parts = [label]
        for mid in models:
            parts.append(metric_callable(mid))
        return parts

    term_order = [
        ("broad_money_growth_pct", "Broad money growth (annual \\%)"),
        ("deposit_interest_rate_pct", "Deposit interest rate (\\%)"),
        ("real_interest_rate_pct", "Real interest rate (\\%)"),
        ("lending_interest_rate_pct", "Lending interest rate (\\%)"),
        ("ln_tourism_arrivals", "Tourism arrivals (Log)"),
        ("hc_human_capital_index", "Human capital index"),
    ]

    control_order = [
        ("trade_pct_gdp", "Trade (\\% GDP)"),
        ("inflation_gdp_deflator_pct", "Inflation (\\%)"),
        ("ln_gdppc", "Log GDP per capita"),
        ("xr_dep_pct", "Exchange-rate depreciation (\\%)"),
    ]

    def build_panel(models: list[str]) -> str:
        rows = []
        # Coef rows
        for term, label in term_order:
            r = row_coef(term, label, models)
            if r is not None:
                rows.append(" & ".join(r) + r" \\")
        rows.append(r"\midrule")
        # Controls
        for term, label in control_order:
            r = row_coef(term, label, models)
            if r is not None:
                rows.append(" & ".join(r) + r" \\")
        rows.append(r"\midrule")
        # Fit stats
        def obs(mid: str) -> str:
            m = pb[pb["model_id"] == mid]
            return str(int(m["total_rows"].iloc[0])) if not m.empty else "—"

        def countries(mid: str) -> str:
            m = pb[pb["model_id"] == mid]
            return str(int(m["countries_used"].iloc[0])) if not m.empty else "—"

        def within_r2(mid: str) -> str:
            m = fe_fs[fe_fs["model_id"] == mid]
            return fmt_num(m["within_r2"].iloc[0], 4) if not m.empty else "—"

        def slope_adj_r2(mid: str) -> str:
            m = fe_fs[fe_fs["model_id"] == mid]
            return fmt_num(m["slope_adjusted_within_r2"].iloc[0], 4) if not m.empty else "—"

        def max_vif(mid: str) -> str:
            m = vif[vif["model_id"] == mid]
            return fmt_num(m["vif"].max(), 2) if not m.empty else "—"

        def cd_p(mid: str) -> str:
            m = diag[diag["model_id"] == mid]
            if m.empty or "pesaran_cd_p_value" not in m.columns:
                return "—"
            val = m["pesaran_cd_p_value"].iloc[0]
            return fmt_pval(val) if not pd.isna(val) else "—"

        for fn, label in [
            (obs, "Observations"),
            (countries, "Countries"),
            (within_r2, "Within $R^2$"),
            (slope_adj_r2, "Slope-adj. $R^2$"),
            (max_vif, "Max VIF"),
            (cd_p, "Pesaran CD $p$"),
        ]:
            parts = row_single(fn, label, models)
            rows.append(" & ".join(parts) + r" \\")
        return "\n".join(rows)

    panel_a = build_panel(panel_a_ids)
    panel_b = build_panel(panel_b_ids)

    # Build the full table
    lines = [
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Two-way fixed-effects regression results with Driscoll–Kraay standard errors}",
        r"\label{tab:main-regression-results}",
        r"\begin{threeparttable}",
        r"\scriptsize",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{l" + "c" * (ncols_a - 1) + "c" * (ncols_b - 1) + "}",
        r"\toprule",
        r" & \multicolumn{5}{c}{Panel A: Headline Models} & \multicolumn{4}{c}{Panel B: Extended Models} \\",
        r"\cmidrule(lr){2-6} \cmidrule(lr){7-10}",
        f" & {col_headers_a} & {col_headers_b} \\\\",
        r"\midrule",
    ]

    # Need to build panel A + B side by side
    # This is complex because the rows need to align. Let me use a simpler approach:
    # two separate tables with a combined caption.

    # Actually, I'll just use a multi-panel approach within one tabular.
    # The simpler approach: Panel A rows with & Panel B rows.

    # For each row in panel_a, find the matching row in panel_b
    # This requires synchronizing which rows are present.

    # Simplest: use the same row structure for both panels even if empty
    # Let me rebuild with fixed row structure.

    # Helper: get term value for a model
    # For the lagged model (M3), all regressors are stored with _lag1 suffix.
    # Term names that end in _lag1 are looked up directly.
    # Other terms: try exact match first; for M3's control variables, also try _lag1 fallback.
    LAGGED_TERMS = {"deposit_interest_rate_pct_lag1"}

    def get_term(mid: str, term: str) -> pd.Series | None:
        if term.endswith("_lag1"):
            r = fe[(fe["model_id"] == mid) & (fe["term"] == term)]
            return r.iloc[0] if not r.empty else None
        r_exact = fe[(fe["model_id"] == mid) & (fe["term"] == term)]
        if not r_exact.empty:
            return r_exact.iloc[0]
        if mid == "M3_lagged_main_model":
            r_lag = fe[(fe["model_id"] == mid) & (fe["term"] == f"{term}_lag1")]
            if not r_lag.empty:
                return r_lag.iloc[0]
        return None

    def fmt_coef(term_res: pd.Series | None) -> str:
        if term_res is None:
            return ""
        return f"{fmt_num(term_res['coef'], 4)}{stars(term_res['p_value'])}"

    def fmt_se(term_res: pd.Series | None) -> str:
        if term_res is None:
            return ""
        return f"({fmt_num(term_res['std_error'], 4)})"

    all_rows_spec = (
        [(t, l, "coef") for t, l in term_order]
        + [(t, l, "coef") for t, l in control_order]
        + [("obs", "Observations", "obs"),
           ("countries", "Countries", "cnt"),
           ("within_r2", "Within $R^2$", "wr2"),
           ("slope_adj_r2", "Slope-adj. $R^2$", "sr2"),
           ("max_vif", "Max VIF", "vif"),
           ("cd_p", "Pesaran CD $p$", "cd")]
    )

    body_parts = []
    for key, label, row_type in all_rows_spec:
        # Coef row
        coef_parts_a = [label]
        coef_parts_b = [""]
        se_parts_a = [""]
        se_parts_b = [""]

        for parts, mids in [(coef_parts_a, panel_a_ids), (coef_parts_b, panel_b_ids)]:
            for mid in mids:
                if row_type == "coef":
                    tr = get_term(mid, key)
                    parts.append(fmt_coef(tr))
                elif row_type == "obs":
                    m = pb[pb["model_id"] == mid]
                    parts.append(str(int(m["total_rows"].iloc[0])) if not m.empty else "—")
                elif row_type == "cnt":
                    m = pb[pb["model_id"] == mid]
                    parts.append(str(int(m["countries_used"].iloc[0])) if not m.empty else "—")
                elif row_type == "wr2":
                    m = fe_fs[fe_fs["model_id"] == mid]
                    parts.append(fmt_num(m["within_r2"].iloc[0], 4) if not m.empty else "—")
                elif row_type == "sr2":
                    m = fe_fs[fe_fs["model_id"] == mid]
                    parts.append(fmt_num(m["slope_adjusted_within_r2"].iloc[0], 4) if not m.empty else "—")
                elif row_type == "vif":
                    m = vif[vif["model_id"] == mid]
                    parts.append(fmt_num(m["vif"].max(), 2) if not m.empty else "—")
                elif row_type == "cd":
                    m = diag[diag["model_id"] == mid]
                    val = m["pesaran_cd_p_value"].iloc[0] if not m.empty else np.nan
                    parts.append(fmt_pval(val) if not pd.isna(val) else "—")

        # SE rows for coefficient type
        if row_type == "coef":
            for parts, mids in [(se_parts_a, panel_a_ids), (se_parts_b, panel_b_ids)]:
                for mid in mids:
                    tr = get_term(mid, key)
                    parts.append(fmt_se(tr))

        has_a = any(p for p in coef_parts_a[1:])
        has_b = any(p for p in coef_parts_b[1:])
        has_se = any(p for p in se_parts_a[1:]) or any(p for p in se_parts_b[1:])

        if not has_a and not has_b:
            continue

        body_parts.append(" & ".join(coef_parts_a + coef_parts_b[1:]) + r" \\")
        if has_se:
            body_parts.append(" & ".join(se_parts_a + se_parts_b[1:]) + r" \\")

    body = "\n".join(body_parts)

    lines.append(body)
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"}")
    lines.extend([
        r"\begin{tablenotes}[flushleft]",
        r"\footnotesize",
        r"\item The dependent variable is FDI net inflows (\% of GDP). All columns use two-way fixed effects with country and year effects and Driscoll--Kraay standard errors (Bartlett kernel). Standard errors in parentheses. *, **, *** denote significance at 10\%, 5\%, 1\% levels. Panel A: headline models. Panel B: robustness models adding tourism arrivals (M6a, M6b) or the human capital index (M7a, M7b) to the M4 and M2 baselines respectively. Samples vary by model due to unbalanced panel coverage.",
        r"\end{tablenotes}",
        r"\end{threeparttable}",
        r"\end{table}",
    ])
    return "\n".join(lines)


# ════════════════════════════════════════════════════════════
# TABLE 2: Descriptive + Correlation + Coverage (merged appendix)
# ════════════════════════════════════════════════════════════
def generate_appendix_table() -> str:
    """Consolidated appendix table: descriptive stats + coverage."""
    raw = pd.read_csv(OUTPUTS / "descriptive_stats.csv", index_col=0)
    var_labels = {
        "fdi_pct_gdp": "FDI (\\% GDP)",
        "broad_money_growth_pct": "Broad money growth (annual \\%)",
        "deposit_interest_rate_pct": "Deposit interest rate (\\%)",
        "real_interest_rate_pct": "Real interest rate (\\%)",
        "lending_interest_rate_pct": "Lending interest rate (\\%)",
        "inflation_gdp_deflator_pct": "Inflation, GDP deflator (\\%)",
        "trade_pct_gdp": "Trade (\\% GDP)",
        "ln_gdppc": "Log GDP per capita",
        "xr_dep_pct": "Exchange-rate depreciation (\\%)",
        "ln_tourism_arrivals": "Tourism arrivals (Log)",
        "hc_human_capital_index": "Human capital index",
    }
    rows = []
    for var, label in var_labels.items():
        if var not in raw.index:
            continue
        r = raw.loc[var]
        count = int(r["count"])
        mean = float(r["mean"])
        std = float(r["std"])
        min_v = float(r["min"])
        max_v = float(r["max"])
        miss_pct = float(r["missing_pct"])
        rows.append(
            f"{label} & {count} & {fmt_num(mean, 3)} & {fmt_num(std, 3)} "
            f"& {fmt_num(min_v, 3)} & {fmt_num(max_v, 3)} & {fmt_num(miss_pct, 1)}\\% \\\\"
        )
    body = "\n".join(rows)
    header = (
        r"Variable & N & Mean & SD & Min & Max & Missing \\"
        r"\midrule"
    )
    return wrap_table(
        header + "\n" + body,
        caption="Descriptive statistics and data coverage for the processed panel (2000--2023)",
        label="tab:descriptive-coverage",
        col_format="lrrrrrl",
        notes=(
            "N = country-year observations. The panel is unbalanced (max 264, min 192 per variable). "
            "FDI is expressed as a percentage of GDP. Monetary proxies have the narrowest coverage "
            "(lending rate: 192 obs). See the country-level audit tables for structural gaps."
        ),
    )


# ════════════════════════════════════════════════════════════
# MAIN
# ════════════════════════════════════════════════════════════
def main():
    TABLES.mkdir(parents=True, exist_ok=True)
    print("Generating consolidated LaTeX tables...")

    write_tex("tab_main_and_diagnostics.tex", generate_main_table())
    write_tex("tab_appendix_descriptive.tex", generate_appendix_table())

    # Remove old individual tables (keep as cleanup note)
    print("\nDone. Now updating methodology_results_interpretation.tex")

if __name__ == "__main__":
    main()
